defaults:
  - _self_
  - launcher: local  # 启动器配置文件
  - data: pusht  # 数据集配置文件
  - model: lewm  # 模型配置文件

output_model_name: lewm_pusht
subdir: ${hydra:job.id}

num_workers: 6  # 数据加载器的工作线程数
train_split: 0.9  # 按比例分割训练集和验证集
seed: 3072  # 随机数种子
img_size: 224  # 图像大小 img_size * img_size
embed_dim: 192  # 隐空间的维度，图像经过 ecoder + projector 后的输出维度
history_size: 3  # 历史步数

trainer:
  max_epochs: 100
  devices: auto
  accelerator: gpu
  precision: bf16
  gradient_clip_val: 1.0

loader:
  batch_size: 100
  num_workers: ${num_workers}
  persistent_workers: True
  prefetch_factor: 3
  pin_memory: True

optimizer:
  type: AdamW
  lr: 5e-5
  weight_decay: 1e-3

num_preds: 1  # 预测步数

loss:
  sigreg:
    weight: 0.09
    kwargs:
      knots: 17
      num_proj: 1024
